import { University, Paper } from './types';

export const UNIVERSITIES: University[] = [
  { id: 'uon', name: 'University of Nairobi', shortName: 'UoN' },
  { id: 'ku', name: 'Kenyatta University', shortName: 'KU' },
  { id: 'strath', name: 'Strathmore University', shortName: 'Strathmore' },
  { id: 'jkuat', name: 'Jomo Kenyatta University of Agriculture and Technology', shortName: 'JKUAT' },
  { id: 'usiu', name: 'United States International University - Africa', shortName: 'USIU' },
  { id: 'moi', name: 'Moi University', shortName: 'Moi' },
  { id: 'egerton', name: 'Egerton University', shortName: 'Egerton' },
  { id: 'maseno', name: 'Maseno University', shortName: 'Maseno' },
  { id: 'cuea', name: 'Catholic University of Eastern Africa', shortName: 'CUEA' },
  { id: 'mmust', name: 'Masinde Muliro University', shortName: 'MMUST' },
];

export const MOCK_PAPERS: Paper[] = [
  {
    id: '1',
    title: 'Introduction to Computer Science',
    university: 'Strathmore',
    courseCode: 'ICS 1101',
    year: 2023,
    uploadedBy: 'Jane Doe',
    fileUrl: '', // Will be handled dynamically or placeholder
    fileType: 'application/pdf',
    uploadDate: '2023-11-15',
    downloads: 124,
    previews: 432,
    category: 'Exam',
  },
  {
    id: '2',
    title: 'Calculus II Final Exam',
    university: 'UoN',
    courseCode: 'SMA 202',
    year: 2022,
    uploadedBy: 'John Smith',
    fileUrl: '',
    fileType: 'application/pdf',
    uploadDate: '2023-01-20',
    downloads: 89,
    previews: 215,
    category: 'Exam',
  },
  {
    id: '3',
    title: 'Business Ethics & Corporate Governance',
    university: 'KU',
    courseCode: 'BBA 300',
    year: 2023,
    uploadedBy: 'Alice Wambui',
    fileUrl: '',
    fileType: 'application/pdf',
    uploadDate: '2023-05-10',
    downloads: 256,
    previews: 890,
    category: 'Exam',
  },
  {
    id: '4',
    title: 'Data Structures and Algorithms',
    university: 'JKUAT',
    courseCode: 'ICS 2204',
    year: 2021,
    uploadedBy: 'Brian K.',
    fileUrl: '',
    fileType: 'application/pdf',
    uploadDate: '2022-12-05',
    downloads: 412,
    previews: 1205,
    category: 'Exam',
  },
  {
    id: '5',
    title: 'Operating Systems CAT 1',
    university: 'Strathmore',
    courseCode: 'ICS 2201',
    year: 2023,
    uploadedBy: 'Mike O.',
    fileUrl: '',
    fileType: 'application/pdf',
    uploadDate: '2023-09-12',
    downloads: 45,
    previews: 180,
    category: 'CAT',
  },
  {
    id: '6',
    title: 'Macroeconomics CAT 2',
    university: 'UoN',
    courseCode: 'ECO 202',
    year: 2023,
    uploadedBy: 'Sarah J.',
    fileUrl: '',
    fileType: 'application/pdf',
    uploadDate: '2023-10-05',
    downloads: 32,
    previews: 94,
    category: 'CAT',
  },
];